### ISSUE TITLE
Terceira Sprint

### ISSUE THREAD

**Issue by John-Luke** [josetvictor/PDS-SystemPapi#14]
### Funcionalidades
  - [x] CRUD Compra (Resolvido em #15)
  - [x] CRUD Venda (Resolvido em #16)
### BD (@Dia-VBC)
  - [ ] Arquivo SQL para padronização (Fica para próxima Sprint)

**Comment by josetvictor** [comment]
Erros da sprint:

--> Inserir Itens;
--> Valor Total;
--> Listagem dos Itens de compra;
